### ISSUE TITLE
User Contributed Notes section title and footer do not follow selected language

### ISSUE THREAD

**Issue by leonardolara** [php/phd#145]
The "User Contributed Notes" title at the bottom of each page is hardcoded in English (in web-php) and will not follow the selected language of the manual. The same occurs for its footer and for the Language Selection combo itself (at the top).

It would be nice if these terms could be translated to the language chosen by the user.

**Comment by haszi** [comment]
I think we could fairly easily add the same type of translation function for these in `web-php` that we're using in PhD.

If nobody beats me to it, I'll try to implement this by the end of next week. To make it work as intended, this will need every language repos' translators input.

**Comment by php-pulls** [comment]
Notes should all be in English, so this is likely why this has on purpose not been translated.

**Comment by cmb69** [comment]
> Notes should all be in English, so this is likely why this has on purpose not been translated.

By the same argument, "Description" just above function signatures should also not be translated, but it is.

And we could change the title to something like "User contributed notes (in English)", and translate that.
