### ISSUE TITLE
Foreign return type syntax

### ISSUE THREAD

**Issue by jjok** [php/phd#16]
I noticed that the documentation still uses Java/C# style return types, even though PHP now has its own syntax for return types. For exmaple:
```
mixed json_decode ( string $json )
```
instead of:
```
json_decode ( string $json ) : mixed
```
It would be nice to see the documentation reflect the syntax of the language.

**Comment by salathe** [comment]
Please use the bug tracking system at bugs.php.net for PhD bugs and feature requests.

Head on over to the bug report page ([bugs.php.net/report.php](https://bugs.php.net/report.php)) to do that. When doing so, please set the "Package affected" field to "Doc Build (PhD) problem", and the "Bug Type" field to "Feature/Change Request".

Many thanks.

**Comment by jjok** [comment]
I've been having a look into this. I think a few changes will need to be made to make this happen.

1. I think a new `returntype` needs to be added in the formatter classes in this package. eg `Package_Generic_XHTML`. I don't think `type` can be reused as it is used anywhere a type is mentioned in the docs, not just return types, and the return type needs to be formatted differently. eg `sprintf(' : <span>%s</span>')`

2. I think the docbook schema in the `phpdoc` repository needs to be updated to allow a new `returntype` element.

```
  <methodsynopsis>
   <methodname>json_decode</methodname>
   <methodparam><type>string</type><parameter>json</parameter></methodparam>
   <methodparam choice="opt"><type>bool</type><parameter>assoc</parameter><initializer>false</initializer></methodparam>
   <methodparam choice="opt"><type>int</type><parameter>depth</parameter><initializer>512</initializer></methodparam>
   <methodparam choice="opt"><type>int</type><parameter>options</parameter><initializer>0</initializer></methodparam>
   <returntype>mixed</returntype>
  </methodsynopsis>
``` 
3. All the existing documentation needs to be updated to the new format. :O

Let me know if I'm on the right tracks. Thanks.

**Comment by jjok** [comment]
Ahh. Yep, will do.
