### ISSUE TITLE
In Firefox, the code from the documentation is copied with Non-breaking spaces (nbsp)

### ISSUE THREAD

**Issue by deevroman** [php/phd#71]
Starting with Firefox 103, it now does not replace nbsp with a normal space. https://bugzilla.mozilla.org/show_bug.cgi?id=359303

Try copying some code from the documentation and pasting it into a text file. (for example from here https://www.php.net/manual/en/function.preg-replace.php)

<img width="614" alt="Снимок экрана 2022-10-30 в 19 15 36" src="https://user-images.githubusercontent.com/25708359/198889411-2c4ca826-40cc-4126-9b44-e8c785b4a601.png">

**Comment by ianthedev** [comment]
> I think we should follow suite and get rid of the non-breaking spaces, and instead prevent space-folding by using `white-space: pre` or such.

Agreed. I'm a Firefox user as well and encountered this issue yesterday.

> Anyhow, this is actually a PhD doc issue.

Should the discussion be moved to PhD doc or continue here? I'm seeing no one here has been assigned to this issue.

**Comment by damianwadley** [comment]
> Should the discussion be moved to PhD doc or continue here?

"Here" _is_ phd.

**Comment by ianthedev** [comment]
> > Should the discussion be moved to PhD doc or continue here?
> 
> "Here" _is_ phd.

I see. Didn't realize "phd" is the same as "PhD doc".

**Comment by cmb69** [comment]
> I'm seeing no one here has been assigned to this issue.

Given that this is an open-source project, you could have submitted a pull request. :)

**Comment by ianthedev** [comment]
> > I'm seeing no one here has been assigned to this issue.
> 
> Given that this is an open-source project, you could have submitted a pull request. :)

I see. Didn't know this issue can be solved that way. Besides, submitting a pull request is current beyond my ability. In fact, I practiced that many years ago by using GitHub Desktop and have long since forgotten the steps. But thanks for letting me know a solution.
