### ISSUE TITLE
Linking to ID on section which is not chunked does not generate a proper link

### ISSUE THREAD

**Issue by Girgias** [php/phd#98]
Linking to an ID that is on an element with `annotations="chunk:false"` does not work.

Related to https://github.com/php/doc-en/issues/3178

**Comment by haszi** [comment]
This seems to be deliberate. Ie. besides not declaring an `xml:id`, this is one of the few ways to mark an element for not being indexed.

With `annotations="chunk:false"` set, `$this->storeInfo()` is not called and the `id` doesn't get indexed.

https://github.com/php/phd/blob/27e3bc3e4a442e16404e36070f12ed33bb231e7d/phpdotnet/phd/Index.php#L373-L386

**Comment by Girgias** [comment]
This is annoying, the main reason I use `annotations="chunk:false"` is to not generate pages for small sections and having a weird table of content.

**Comment by alfsb** [comment]
On a system similar to `phd`, I automatically generate `xml:id`s for any entity that is linked or is root chunk that does not have one.

This permit to control chunking entirely on rendering system, and without depending on XML or Markdown to annotate the things in a specific way for arbitrary render system.

**Comment by haszi** [comment]
There are two methods in `Index` (`UNDEF()` and `format_example()`) that have the following line of code

```php
$this->storeInfo($name, $id, $this->currentchunk, false);
```
which does store the element's `$id` being in the file `$this->currentchunk` and marking it as a non-chunk (the last, `false` argument). I think this might be useful for this use case by adding it to the `else` clause of the last conditional in that block of code in my previous message:

https://github.com/php/phd/blob/27e3bc3e4a442e16404e36070f12ed33bb231e7d/phpdotnet/phd/Index.php#L382-L386

I haven't tested this yet, but seems reasonable to me.

**Comment by haszi** [comment]
I've got it working by adding an `else` clause like this:

```php
  else {
      $this->storeInfo($name, $id, $this->currentchunk, false);
      $this->appendID();
  }
```

I have a relatively hard time writing a test for it though. `Index` has a hardcoded database and private properties, `Config` is working with a magic method that sets and gets properties, `TestRender` has hardcoded `Render`, `Reader` and `Index` instances. I think I'll refactor all this to work with constructor dependency injection before I submit a PR for this issue here, if that is OK.

**Comment by Girgias** [comment]
Yeah that's totally fine, this whole project could use some love as it's been on life support since the initial contributor stopped in 2012 (For reference you are the 4th highest contributor to PhD since July 2012: https://github.com/php/phd/graphs/contributors?from=2012-06-22&to=2024-02-24&type=c
